{ name = "presto-dom"
, dependencies =
  [ "aff"
  , "arrays"
  , "control"
  , "effect"
  , "either"
  , "exceptions"
  , "foldable-traversable"
  , "foreign"
  , "foreign-generic"
  , "foreign-object"
  , "functions"
  , "halogen-vdom"
  , "hyrule"
  , "integers"
  , "lists"
  , "lite-decode"
  , "maybe"
  , "newtype"
  , "prelude"
  , "presto"
  , "purs-react"
  , "refs"
  , "strings"
  , "tracker"
  , "transformers"
  , "tuples"
  , "typelevel-prelude"
  , "unsafe-coerce"
  , "web-dom"
  , "web-events"
  ]
, packages = ./packages.dhall
, sources = [ "src/**/*.purs" ]
}
